### ISSUE TITLE
DOMException: Failed to execute 'insertRule'

### ISSUE THREAD

**Issue by rhercb** [chromaui/storybook-addon-pseudo-states#26]
I have run into this issue when adding this plugin for storybook.

```
DOMException: Failed to execute 'insertRule' on 'CSSStyleSheet': Failed to parse the rule '.btn-primary:hover:not(:active):not(:disabled):not(.disabled), .pseudo-hover.pseudo-active .btn-primary:not():not(:disabled):not(.disabled) { background-color: rgb(74, 143, 33); border-color: rgb(67, 118, 43); }'.
```

    
```
at rewriteStyleSheets (http://localhost:6006/vendors-node_modules_storybook_addon-actions_dist_esm_preset_addArgs_js-generated-config-entr-fcfaa8.iframe.bundle.js:45960:21)
    at Object.<anonymous> (http://localhost:6006/vendors-node_modules_storybook_addon-actions_dist_esm_preset_addArgs_js-generated-config-entr-fcfaa8.iframe.bundle.js:45994:10)
    at http://localhost:6006/vendors-node_modules_storybook_addon-actions_dist_esm_preset_addArgs_js-generated-config-entr-fcfaa8.iframe.bundle.js:5199:14
    at Array.forEach (<anonymous>)
    at Channel.handleEvent (http://localhost:6006/vendors-node_modules_storybook_addon-actions_dist_esm_preset_addArgs_js-generated-config-entr-fcfaa8.iframe.bundle.js:5198:19)
    at handler (http://localhost:6006/vendors-node_modules_storybook_addon-actions_dist_esm_preset_addArgs_js-generated-config-entr-fcfaa8.iframe.bundle.js:5124:16)
    at Channel.emit (http://localhost:6006/vendors-node_modules_storybook_addon-actions_dist_esm_preset_addArgs_js-generated-config-entr-fcfaa8.iframe.bundle.js:5131:9)
    at http://localhost:6006/vendors-node_modules_storybook_addon-actions_dist_esm_preset_addArgs_js-generated-config-entr-fcfaa8.iframe.bundle.js:8503:43
    at _callee12$ (http://localhost:6006/vendors-node_modules_storybook_addon-actions_dist_esm_preset_addArgs_js-generated-config-entr-fcfaa8.iframe.bundle.js:8390:38)
    at tryCatch (http://localhost:6006/vendors-node_modules_storybook_addon-actions_dist_esm_preset_addArgs_js-generated-config-entr-fcfaa8.iframe.bundle.js:44486:40)
```
Looks like plugin, maby doesn't know how to read .scss file styles?

**Comment by ZebraFlesh** [comment]
Similar issue here. I was able to track it down to the 1.0.2 release -- 1.0.1 and 1.0.0 both work well for me, so pinning to that for now.

**Comment by m-akinc** [comment]
I think the original issue has since been fixed and the issue @Sir-Genius commented about is covered by #37 (as he also pointed out).

**Comment by m-akinc** [comment]
Issue should be marked closed as fixed.
