### ISSUE TITLE
Cannot find module '@storybook/manager-api'  

### ISSUE THREAD

**Issue by dermyhughes** [chromaui/storybook-addon-pseudo-states#74]
Hi.

Trying to install `storybook-addon-pseudo-states` to our Storybook v6.5.16

`npm i -D storybook-addon-pseudo-states`

Added `'storybook-addon-pseudo-states'` to the addons array in our `.storybook/main.js`

Storybook builds but the button is not available in the toolbar, no states styles are created when setting the parameters in the story.

I am getting the following error in my console:

```
vendors-node_modules_etchteam_storybook-addon-status_register_js-node_modules_storybook_addon-3f5fbe.manager.bundle.js:129599
Uncaught Error: Cannot find module '@storybook/manager-api'
    at webpackMissingModule (vendors-node_modules_etchteam_storybook-addon-status_register_js-node_modules_storybook_addon-3f5fbe.manager.bundle.js:129599:96)
    at ./node_modules/storybook-addon-pseudo-states/dist/manager.js (vendors-node_modules_etchteam_storybook-addon-status_register_js-node_modules_storybook_addon-3f5fbe.manager.bundle.js:129599:193)
    at __webpack_require__ (runtime~main.manager.bundle.js:23:42)
    at __webpack_exec__ (main.manager.bundle.js:69:48)
    at main.manager.bundle.js:70:1162
    at __webpack_require__.O (runtime~main.manager.bundle.js:60:23)
    at main.manager.bundle.js:71:56
    at webpackJsonpCallback (runtime~main.manager.bundle.js:319:39)
    at main.manager.bundle.js:1:91
```

Am I missing something?

**Comment by dermyhughes** [comment]
Reverting to v1.15.5 works. I'm assuming the jump to v2 only works with Storybook 7?

**Comment by thafryer** [comment]
@dermyhughes Thanks for reaching out. These changes are for 7.0+ only, which is the main reason for the major version bump.
